baseURL = "http://dieter.plaetinck.be"
languageCode = 'en-us'
title = "Dieter's blog"
theme = "hugo-blog-awesome"
buildDrafts = false
buildFuture = false
uglyUrls = false

[params]
  commentServer = "http://plaetinck.be:5888/comments"

[[menu.main]]
    name = "blog"
    url = "/"
    weight = 9
[[menu.main]]
    name = "about"
    url = "/about"
    weight = 10

[[menu.main]]
    name = "talks"
    url = "/talks"
    weight = 20

[[menu.main]]
    name = "Github"
    pre = "<i class='fa fa-heart'></i>"
    weight = 40
    url = "https://github.com/Dieterbe"
[[menu.main]]
    name = "tweets"
    pre = "<i class='fa fa-road'></i>"
    weight = 30
    url = "https://twitter.com/Dieter_be"
