baseURL = "https://dieter-dev.plaetinck.be"
languageCode = 'en-us'
title = "Dieter's blog"
theme = "hugo-blog-awesome"
defaultContentLanguage = "en-gb"
enableEmoji = true
staticDir = "static"
ignoreLogs = ['warning-frontmatter-params-overrides'] # to define images in posts. i don't think i define them in site config

[params]
commentServer = "https://dieter-dev.plaetinck.be/comments"
rssFeedDescription = "full" # available options: 1) summary 2) full


[[menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    weight = 10
[[menu.main]]
    pageRef="posts"
    name = 'Posts'
    weight = 20
[[menu.main]]
    pageRef="projects"
    name = 'Projects'
    weight = 30
[[menu.main]]
    pageRef="about"
    name = 'About'
    weight = 40
[[menu.main]]
    pageRef="talks"
    name = "Talks"
    weight = 50

[params.author]
  avatar = "grafana_dieter_plaetinck.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Dieter's blog"
  name = "Dieter Plaetinck"
  description = "Open Source is life. Ex-Grafana Labs founding engineer. Loves mountain sports. Trying to be helpful to startups"

[[params.profiles]]
name = "GitHub"
url = "https://github.com/Dieterbe"

[[params.profiles]]
name = "Twitter"
url = "https://twitter.com/Dieter_be"

[[params.profiles]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/dieterplaetinck"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Dieterbe"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/Dieter_be"

[[params.socialIcons]]
name = "linkedIn"
url = "https://linkedin.com/in/dieterplaetinck"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[services]
[services.rss]
limit = 5
